### ISSUE TITLE
User not a sudoer

### ISSUE THREAD

**Issue by bjornborg** [chalmers-revere/opendlv.os#1]
The created user is not automatically a sudoer:
- reverian is not in the sudoers file.  This incident will be reported.
Moreover, it causes problems for some installation steps where root privileges are required.

**Comment by olbender** [comment]
This is the intended behaviour. We do not want the normal user to get any root privileges. @chrberger is this a valid default setting? If we would like to change this, I will add a new "setup-user-sudo.sh" to only include this on demand (not by default).

**Comment by chrberger** [comment]
@olbender I think it would be good to minimize the allowed permissions; so, I vote for that the normal user is not sudo-able.

**Comment by olbender** [comment]
Great, then we close this issue without any change.
