### ISSUE TITLE
Enable swap

### ISSUE THREAD

**Issue by olbender** [chalmers-revere/opendlv.os#10]

**Comment by bjornborg** [comment]
What happens if the command line fails because of the device is busy? It happened to me :(. https://github.com/chalmers-revere/opendlv.os/blob/master/x86/install.sh#L24

**Comment by olbender** [comment]
Oh.. This worked for me so far. Why is it busy?

**Comment by bjornborg** [comment]
I have no idea, should you introduce a check for it?

**Comment by olbender** [comment]
Done

**Comment by chrberger** [comment]
How much swap space do we have by default now?
