### ISSUE TITLE
Improving console prompt: path & git branch & aliases

### ISSUE THREAD

**Issue by fgiaimo** [chalmers-revere/opendlv.os#23]
To be added to the .bashrc file (replacing the current PS1 variable):

`parse_git_branch() { `
 `  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/' `
`} `
`#Using colored prompt by default `
`PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(parse_git_branch)\$ ' `
`alias ll='ls -alF' `
`alias la='ls -A' `

**Comment by olbender** [comment]
Not done. Should not be relevant for a production system.
