### ISSUE TITLE
Docker and docker-compose not included

### ISSUE THREAD

**Issue by bjornborg** [chalmers-revere/opendlv.os#3]

**Comment by chrberger** [comment]
Really? Are you sure that we are using the right OpenDLV.OS images?

**Comment by bjornborg** [comment]
I am installing it as I am typing right now on the beaglebone :).

**Comment by bjornborg** [comment]
It seems like a lot of packages are not included. This might be coupled to the root privileges issues.

**Comment by olbender** [comment]
This sounds a bit strange, but I will check. This is also regarding the arm-bbb install (please indicate the platform in future issues).

**Comment by bjornborg** [comment]
The problem is that, the installation assumes that there is an internet connection. If there is no connection the installation won't proceed. Problem located, and problem solved.
