### ISSUE TITLE
NTP setup script

### ISSUE THREAD

**Issue by olbender** [chalmers-revere/opendlv.os#32]
Some clients would perhaps want NTP instead of PTP. Add a setup script for this.

**Comment by ghost** [comment]
Should be on Meinberg level, https://github.com/chalmers-revere/opendlv-platform-snowfox/issues/10 
https://github.com/chalmers-revere/opendlv-platform-rhino/issues/8

**Comment by chrberger** [comment]
Confirmed with Axis camera
