### ISSUE TITLE
Wireless configuration should work now.

### ISSUE THREAD

**Issue by CaeruleusAqua** [chalmers-revere/opendlv.os#4]
I created a new udev-rule under "/etc/udev/rules.d/70-wireless-name.rules"
to fix the device-Name (if we change the wireless adapter we need to modify the Macadress in that file).
All wireless profiles are now pointing to the wlan0 interface, and will be enabled by netctl-auto
depending on our location (AstaZero or Revere).
You can disable/enable this using "systemctl enbale/disable netctl-auto@wlan0.service"

**Comment by chrberger** [comment]
Is this part of the automated install scripts as well?

**Comment by CaeruleusAqua** [comment]
No, Ola will take care of this..

**Comment by chrberger** [comment]
That's still unclear to me: Is this a manual step each time we reset a car PC?

**Comment by olbender** [comment]
No, I think this is info for me to consider for the next version of the installation scripts.

**Comment by chrberger** [comment]
Okay, so it will be automated later?

**Comment by CaeruleusAqua** [comment]
The PC will automatically connect to the AstaZero and Revere wlan if powered up.
If we setup a new linux on the PC the changes are lost. Ola said he will add the changes to the 
automated install scripts later, so that we down't lost them in future.

Does that answer your question?

**Comment by olbender** [comment]
Well, this was already the intended behaviour, but apparently something did not work as expected. I will use the input from Julian and find a better solution for the next version of the automated install. However, there is currently a problem that we get a 1.5 min boot delay if no wifi interface is present. This must also be fixed.

**Comment by CaeruleusAqua** [comment]
This fixes also the 1.5 min boot delay!

**Comment by olbender** [comment]
Ok, I saw that delay today, but perhaps you made further improvement. I will take a look and test it for the next release. Thanks!

**Comment by ghost** [comment]
Not relevant anymore. We use wired internet at REVERE & 4G modem outside REVERE.
