### ISSUE TITLE
Set static IPs of network interfaces

### ISSUE THREAD

**Issue by olbender** [chalmers-revere/opendlv.os#40]
For example, to enable radars on Snowfox:
sudo ifconfig enp11s0 192.168.242.25 up
sudo ifconfig enp10s0 192.168.241.25 up
sudo ifconfig enp5s0 192.168.244.25 up

And to enable the BoB system on Snowfox:
sudo ifconfig enp0s25 192.168.1.1 netmask 255.255.255.0 up
sudo ifconfig enp0s25 mtu 4088

**Comment by ghost** [comment]
Not relevant for radars, BOB is done manually on Brick PC.
