### ISSUE TITLE
Please add the git branch visualization to `PS1`

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv.os#46]
To add to the ~/.bashrc file: 
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/' }
and then modify the two "PS1=..." lines in the true and false branches of the if statement "if [ "$color_prompt" = yes ]; then" : just add "$(parse_git_branch) " before the '\$' towards the end of those lines.

**Comment by ghost** [comment]
moved to https://github.com/chalmers-revere/opendlv-platform-snowfox/issues/14 & https://github.com/chalmers-revere/opendlv-platform-rhino/issues/10
