### ISSUE TITLE
Disabling eee on all network interfaces

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv.os#48]
Please add `ethtool --set-eee X eee off` where X is an interface name like `eno1` to disable the energy efficiency control. Disabling it improves the PTP performance.

**Comment by ghost** [comment]
https://github.com/chalmers-revere/opendlv-platform-snowfox/issues/15        
https://github.com/chalmers-revere/opendlv-platform-rhino/issues/11,                                 https://github.com/chalmers-revere/opendlv-platform-snowfox/issues/16
